### ISSUE TITLE
FDP-to-RDF-Datasets have no description/title in OS-Explorer

### ISSUE THREAD

**Issue by schmaluk** [openbudgets/platform#35]
![fdp2rdf_explorer](https://cloud.githubusercontent.com/assets/17597578/24157340/698a6efc-0e59-11e7-8959-a70f32d4f162.PNG)
It seems that the datasets imported by the FDP-to-RDF-pipeline have no title or description in the OS-Explorer. 

Just an info regarding the integration: The Cache in Rudolf is refreshed every 30 mins. Only if the cache has been refreshed the datasets will show up in the OS-Explorer: http://eis-openbudgets.iais.fraunhofer.de/explorer/
They do show up after that. However without any name unfortunately.

(Might be that not the proper fields/information had been provided in OS-packager in the first place. Though I inserted a description in the Packager)

**Comment by marek-dudas** [comment]
So could someone tell me where does OS-Explorer search for the dataset name, publisher, description or anything else that is not shown, so I can check the FDP2RDF output? It might be just the case that the name&description ends up in a different property value than expected by OS-Explorer.

**Comment by marek-dudas** [comment]
The latest update of FDP-to-RDF pipeline, commited yesterday and to-be-deployed on the Fraunhofer server, might fix this as it outputs dataset metadata more accurately. However, it would still be helpful to know what are the properties and values OS-explorer needs to display dataset info properly - as I asked above.

**Comment by jindrichmynarz** [comment]
I think this question needs clarification, at least for me.

It seems to me that the issue is not about OS Explorer, but instead about Rudolf that provides the OS Explorer with data sourced from the RDF datasets produced by the FDP to RDF pipeline. If I understand this correctly, the question is what metadata is required by Rudolf to be able to produce these views? @larjohn, can you tell?

**Comment by skarampatakis** [comment]
From what I have found, is that rudolf uses a query like this to get the dataset titles along wih other data.
```
prefix qb: <http://purl.org/linked-data/cube#> 

select distinct ?dataset ?dsd (GROUP_CONCAT(distinct ?titles; separator='||') AS ?titles)
where {
?dataset a qb:DataSet .
?dataset qb:structure ?dsd .
?dataset <http://purl.org/dc/terms/title> ?title .
BIND (CONCAT(LANG(?title),'=',?title) AS ?titles)
}
```
So the language tag is used to construct the titles. Datasets from FDP2RDF do not have a language tag along with the dc:title property. Either this should be relaxed inside rudolf, or define a language tag for the property literal value. However, this would require to somehow define the language tag from the Packager.
@larjohn may have more to say.

**Comment by jindrichmynarz** [comment]
Is `{language1}={title1}||{language2}={title2}` format what OS Viewer requires?

**Comment by skarampatakis** [comment]
I suppose so. If you run this query on virtuoso you will see the results and notice that in datasets from FDP2RDF the result is just "=dataset". So either rudolf should set a default or the pipeline.

**Comment by marek-dudas** [comment]
Thanks for the analysis. So since OS-Packager UI is English only and there is no way of defining language in FDP, I suppose I can add English language tag to metadata literals in the pipeline by default.

**Comment by jindrichmynarz** [comment]
Is the problem a missing language tag or missing dataset title?

I don't think adding `@en` by default is a good solution, since non-English labels are also quite prominent. I think this is a presentation issue. The logic what to do when no English label is available should be a part of OS Viewer.

**Comment by pwalsh** [comment]
The Viewer supports translations. We have several already. More can be contributed:

https://github.com/openspending/os-viewer/tree/master/translations


These are translations of the *app* interface. We don't support translations in the data itself, in Fiscal Data Package, and by extension, all the tools that depend on it.

**Comment by jindrichmynarz** [comment]
If translations in data are not supported by OS Viewer, then why is Rudolf producing labels annotated with language tags?

**Comment by pwalsh** [comment]
> If translations in data are not supported by OS Viewer, then why is Rudolf producing labels annotated with language tags?

No idea.

**Comment by pwalsh** [comment]
@badmotor @larjohn

Should this be kept open, for action, or not. If it should be actioned, let's assign a single person with responsibility, and get an estimate on time and due date.

**Comment by larjohn** [comment]
This will be fixed soon.

**Comment by larjohn** [comment]
This has been fixed

**Comment by skarampatakis** [comment]
Seems to be still an issue on OS Explorer. Should it be updated?

![image](https://user-images.githubusercontent.com/2419820/27171912-ef7598d4-51bb-11e7-8145-24a2e5a8e426.png)

**Comment by larjohn** [comment]
Waiting for integration to update the docker config file

**Comment by liyakun** [comment]
@larjohn I have updated Rudolf to the latest version on the Fraunhofer server.

**Comment by larjohn** [comment]
It doesn't run so that I can check

**Comment by skarampatakis** [comment]
check on apps.openbudgets.eu

Στις 26 Ιουν 2017 23:48, ο χρήστης "Lazaros Ioannidis" <
notifications@github.com> έγραψε:

**Comment by larjohn** [comment]
@skarampatakis  How to make it show a package without a title?

**Comment by liyakun** [comment]
As we are not going to use os-expolrer anymore at the Fraunhofer server, so I will close this issue.
